### ISSUE TITLE
i2p broken

### ISSUE THREAD

**Issue by sharkbit** [BiglySoftware/BiglyBT-plugin-azneti2phelper#1]
Seems like a recent update has broken i2p. (BETA)

I2P is the only network enabled,  Old torrents and new items added via Swarm Discovery have a Source status that shows:
```
type     Details         Status 	
------   -------         ------
DHT      DTH: Running	 Disabled: Network not enabled
```

I2P DTH Status only has activity and shows connectivity to 900+ peers

**But the Distributed Tracker shows torrents are being seen but  notes them as 'Not monitoring: Network not enabled'**

PEX & Peer Cache are the only thing keeping me alive.

System:
Java 1.8.0_391 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
**B3.5.0.1_B10/4 az3**

**Comment by parg** [comment]
Right, DHT = public DHT, hence the network is disabled.

When you say "Distributed Tracker" what view are you referring to?

**Comment by sharkbit** [comment]
Okay, so witch DB would track i2p data?  mlDHT?

**Comment by parg** [comment]
The separate I2P DHT...

**Comment by sharkbit** [comment]
Ok the "I2P Only DHT Stats" show activity and data being sent and received.  

BUT I use swarm discovery and click on a torrent (with only i2P enabled) it never finds a peer / seed (+7 days..)  Even after clearing swarm discovery and letting the list repopulate with I2P only data  it will not download the recent items anymore.

**Comment by parg** [comment]
There is no segregated I2P Swarm Discoveries, things found via it aren't guaranteed to have I2P trackers (check out the trackers on the content, the host names would need to end in ".i2p" to be I2P trackers)

If you want to download torrents over I2P then you are going to have most success if you find torrents within the I2P network rather than random public ones.
